name: Merryclean
markdown: redcarpet
pygments: true
timezone: Europe/Paris
permalink: /:title.html
baseurl: /Merryclean/
url: http://gillesbertaux.github.io
paginate: 5
paginate_path: 'page:num'
destination: _site/